<script setup lang="ts">
import ApiTable from '../components/docs/ApiTable.vue';
import ExampleBlock from '../components/docs/ExampleBlock.vue';
import PageAnchor from '../components/docs/PageAnchor.vue';
import DynamicDrawGeometryDemo from '../examples/DynamicDrawGeometryDemo.vue';
import geometrySource from '../examples/DynamicDrawGeometryDemo.vue?raw';

const anchors = [{ id: 'overview', label: '概述' }, { id: 'examples', label: '代码演示', children: [{ id: 'example-point-line-polygon', label: '点、线、面绘制' }] }, { id: 'api', label: 'API', children: [{ id: 'api-types', label: '类型定义', children: [{ id: 'api-type-drawtype', label: 'DrawType' }, { id: 'api-type-idrawbase', label: 'IDrawBase' }, { id: 'api-type-idrawevent', label: 'IDrawEvent' }, { id: 'api-type-idrawpoint', label: 'IDrawPoint' }, { id: 'api-type-idrawline', label: 'IDrawLine' }, { id: 'api-type-idrawpolygon', label: 'IDrawPolygon' }, { id: 'api-type-igeometryfill', label: 'IGeometryFill' }] }, { id: 'api-methods', label: '方法' }] }, { id: 'tips', label: '注意事项' }];
const propertyCols = [{ prop: 'name', label: '属性名', width: 180, presentation: 'property' as const }, { prop: 'desc', label: '说明', width: 330 }, { prop: 'type', label: '类型', width: 260, monospace: true }];
const methodCols = [{ prop: 'name', label: '方法名', width: 220, presentation: 'method' as const }, { prop: 'desc', label: '说明', width: 350 }, { prop: 'params', label: '参数', width: 260, monospace: true }, { prop: 'returns', label: '返回值', width: 120, monospace: true }];
const baseRows = [{ name: 'keepGraphics', desc: '完成后是否保留成果，默认保留。', type: 'boolean?' }, { name: 'callback', desc: '接收绘制生命周期事件。', type: '(event: <a href="#api-type-idrawevent">IDrawEvent</a>) =&gt; void' }];
const eventRows = [{ name: 'type', desc: '绘制生命周期类型。', type: '<a href="#api-type-drawtype">DrawType</a>' }, { name: 'eventPosition', desc: '事件发生位置。', type: 'Coordinate | Coordinate[]' }, { name: 'featurePosition', desc: '完成要素的坐标。', type: 'Coordinate | Coordinate[]?' }, { name: 'feature', desc: '完成后的要素。', type: 'Feature&lt;Geometry&gt;?' }, { name: 'ctlPoints', desc: '标绘控制点。', type: 'Coordinate[]?' }, { name: 'center', desc: '圆心。', type: 'Coordinate?' }, { name: 'radius', desc: '圆半径。', type: 'number?' }];
const pointRows = [...baseRows, { name: 'limit', desc: '最大绘制次数；0 表示持续绘制。', type: 'number?' }, { name: 'size', desc: '点大小。', type: 'number?' }, { name: 'fillColor', desc: '点填充色。', type: 'string?' }];
const lineRows = [...baseRows, { name: 'backgroundStroke', desc: '主描边下方的背景描边。', type: '<a href="/components/point-layer#api-type-istroke">IStroke</a>?' }, { name: 'strokeColor', desc: '描边颜色。', type: 'string?' }, { name: 'strokeWidth', desc: '描边宽度。', type: 'number?' }];
const polygonRows = [...lineRows, { name: 'fillColor', desc: '填充颜色。', type: 'string?' }, { name: 'fill', desc: '填充样式，优先于 fillColor。', type: '<a href="#api-type-igeometryfill">IGeometryFill</a>?' }];
const methods = [{ name: 'drawPoint', desc: '开始绘制点。', params: 'param?: <a href="#api-type-idrawpoint">IDrawPoint</a>', returns: 'void' }, { name: 'drawLine', desc: '开始绘制线。', params: 'param?: <a href="#api-type-idrawline">IDrawLine</a>', returns: 'void' }, { name: 'drawPolygon', desc: '开始绘制面。', params: 'param?: <a href="#api-type-idrawpolygon">IDrawPolygon</a>', returns: 'void' }];
</script>

<template>
  <div class="doc-page-layout"><article class="doc-page"><header class="doc-hero"><span class="doc-hero__eyebrow">地图交互</span><h1>基础几何绘制</h1><p>采集点、线、面等普通地图要素，并在回调中接收绘制结果。</p></header><section id="overview" class="doc-prose"><h2 class="doc-h2">概述</h2><p>基础绘制方法共享 <code><a href="#api-type-idrawbase">IDrawBase</a></code> 配置；完成、移动和退出等过程统一通过 <code><a href="#api-type-idrawevent">IDrawEvent</a></code> 回调。</p></section><section id="examples" class="doc-prose"><h2 class="doc-h2">代码演示</h2><div id="example-point-line-polygon"><ExampleBlock title="点、线、面绘制" :description="'分别调用 <code class=&quot;code-fn&quot;><a href=&quot;#api-methods&quot;>drawPoint</a></code>、<code class=&quot;code-fn&quot;><a href=&quot;#api-methods&quot;>drawLine</a></code> 和 <code class=&quot;code-fn&quot;><a href=&quot;#api-methods&quot;>drawPolygon</a></code>。'" :source="geometrySource"><template #preview><DynamicDrawGeometryDemo /></template></ExampleBlock></div></section><section id="api" class="doc-prose"><h2 class="doc-h2">API</h2><h3 id="api-types" class="doc-h3">类型定义</h3><h4 id="api-type-drawtype" class="doc-h4">DrawType</h4><p><code>Drawstart | Drawing | Drawend | DrawingClick | Drawexit</code></p><h4 id="api-type-idrawbase" class="doc-h4">IDrawBase</h4><ApiTable :columns="propertyCols" :rows="baseRows" /><h4 id="api-type-idrawevent" class="doc-h4">IDrawEvent</h4><ApiTable :columns="propertyCols" :rows="eventRows" /><h4 id="api-type-idrawpoint" class="doc-h4">IDrawPoint</h4><ApiTable :columns="propertyCols" :rows="pointRows" /><h4 id="api-type-idrawline" class="doc-h4">IDrawLine</h4><ApiTable :columns="propertyCols" :rows="lineRows" /><h4 id="api-type-idrawpolygon" class="doc-h4">IDrawPolygon</h4><ApiTable :columns="propertyCols" :rows="polygonRows" /><h4 id="api-type-igeometryfill" class="doc-h4">IGeometryFill</h4><p><code>普通颜色填充或纹理填充配置；详见图层填充类型。</code></p><h3 id="api-methods" class="doc-h3">方法</h3><ApiTable :columns="methodCols" :rows="methods" /></section><section id="tips" class="doc-prose"><h2 class="doc-h2">注意事项</h2><p>线和面绘制时右键结束当前会话。</p></section></article><aside class="doc-page-layout__aside"><PageAnchor title="基础几何绘制" :items="anchors" /></aside></div>
</template>
