<script setup lang="ts">
import ApiTable from '../components/docs/ApiTable.vue';
import ExampleBlock from '../components/docs/ExampleBlock.vue';
import PageAnchor from '../components/docs/PageAnchor.vue';
import DynamicDrawEditingDemo from '../examples/DynamicDrawEditingDemo.vue';
import editingSource from '../examples/DynamicDrawEditingDemo.vue?raw';
import { editableDynamicDrawGeometries } from '../config/dynamicDrawGeometries';

const anchors = [{ id: 'overview', label: '概述' }, { id: 'examples', label: '代码演示', children: [{ id: 'example-edit-plot', label: '编辑标绘成果' }] }, { id: 'api', label: 'API', children: [{ id: 'api-types', label: '类型定义', children: [{ id: 'api-type-modifytype', label: 'ModifyType' }, { id: 'api-type-imodifyevent', label: 'IModifyEvent' }, { id: 'api-type-ieditparam', label: 'IEditParam' }, { id: 'api-type-iplotedit-event-payload', label: 'IPlotEditEventPayload' }] }, { id: 'api-methods', label: '方法' }] }, { id: 'tips', label: '注意事项' }];
const propertyCols = [{ prop: 'name', label: '属性名', width: 190, presentation: 'property' as const }, { prop: 'desc', label: '说明', width: 330 }, { prop: 'type', label: '类型', width: 280, monospace: true }];
const methodCols = [{ prop: 'name', label: '方法名', width: 280, presentation: 'method' as const }, { prop: 'desc', label: '说明', width: 310 }, { prop: 'params', label: '参数', width: 280, monospace: true }, { prop: 'returns', label: '返回值', width: 120, monospace: true }];
const modifyRows = [{ name: 'type', desc: '编辑生命周期类型。', type: '<a href="#api-type-modifytype">ModifyType</a>' }, { name: 'position', desc: '编辑后的坐标。', type: 'Coordinate | Coordinate[]?' }, { name: 'plotParam', desc: '标绘编辑数据。', type: '<a href="#api-type-iplotedit-event-payload">IPlotEditEventPayload</a>?' }];
const editRows = [{ name: 'feature', desc: '待编辑的要素。', type: 'Feature&lt;Geometry&gt;' }, { name: 'isShowUnderlay', desc: '编辑标绘时是否显示参考底图。', type: 'boolean?' }, { name: 'callback', desc: '接收编辑生命周期事件。', type: '(event: <a href="#api-type-imodifyevent">IModifyEvent</a>) =&gt; void' }];
const plotPayloadRows = [{ name: 'index', desc: '当前控制点索引。', type: 'number?' }, { name: 'coordinate', desc: '当前控制点坐标。', type: 'Coordinate?' }, { name: 'points', desc: '全部控制点。', type: 'Coordinate[]' }, { name: 'coords', desc: '实时几何坐标。', type: 'Coordinate[] | Coordinate[][]' }, { name: 'plotType', desc: '标绘类型。', type: 'EPlotType?' }];
const methods = editableDynamicDrawGeometries.map(({ editMethod: name, editDescription: desc }) => ({ name, desc, params: 'param: <a href="#api-type-ieditparam">IEditParam</a>', returns: 'void' }));
</script>

<template>
  <div class="doc-page-layout"><article class="doc-page"><header class="doc-hero"><span class="doc-hero__eyebrow">地图交互</span><h1>几何编辑</h1><p>调整已保存的普通几何或高级标绘，并从回调中读取编辑过程。</p></header><section id="overview" class="doc-prose"><h2 class="doc-h2">概述</h2><p>编辑方法接收 <code><a href="#api-type-ieditparam">IEditParam</a></code>；回调中的 <code><a href="#api-type-imodifyevent">IModifyEvent</a></code> 用于识别过程状态和标绘控制点。</p></section><section id="examples" class="doc-prose"><h2 class="doc-h2">代码演示</h2><div id="example-edit-plot"><ExampleBlock title="编辑标绘成果" :description="'选择图形后先完成绘制，再调用本页方法表中的 <code class=&quot;code-fn&quot;><a href=&quot;#api-methods&quot;>edit*</a></code> 方法进入编辑；右键退出。'" :source="editingSource"><template #preview><DynamicDrawEditingDemo /></template></ExampleBlock></div></section><section id="api" class="doc-prose"><h2 class="doc-h2">API</h2><h3 id="api-types" class="doc-h3">类型定义</h3><h4 id="api-type-modifytype" class="doc-h4">ModifyType</h4><p><code>Modifying | Modifyexit</code></p><h4 id="api-type-imodifyevent" class="doc-h4">IModifyEvent</h4><ApiTable :columns="propertyCols" :rows="modifyRows" /><h4 id="api-type-ieditparam" class="doc-h4">IEditParam</h4><ApiTable :columns="propertyCols" :rows="editRows" /><h4 id="api-type-iplotedit-event-payload" class="doc-h4">IPlotEditEventPayload</h4><ApiTable :columns="propertyCols" :rows="plotPayloadRows" /><h3 id="api-methods" class="doc-h3">方法</h3><ApiTable :columns="methodCols" :rows="methods" /></section><section id="tips" class="doc-prose"><h2 class="doc-h2">注意事项</h2><p>编辑开始前必须传入已保存的要素；右键会结束当前编辑会话。</p></section></article><aside class="doc-page-layout__aside"><PageAnchor title="几何编辑" :items="anchors" /></aside></div>
</template>
